{
 "title": "QoE CMCD fields",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,15m, 30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "percentile", "label": "Percentiles aggregation", "query": "10,50,90,95,99" },
   {
    "name": "country",
    "label": "Country",
    "query": "SELECT DISTINCT (c_country), count(*) AS CNT\nFROM $__database.$__table\nWHERE $__timeFilter\nGROUP BY c_country\nORDER BY CNT DESC"
   },
   {
    "name": "asn",
    "label": "ASN",
    "query": "SELECT DISTINCT (asn), count(*) AS CNT\nFROM $__database.$__table\nWHERE $__timeFilter\nGROUP BY asn\nORDER BY CNT DESC"
   },
   {
    "name": "device",
    "label": "Device Type",
    "query": "CloudFront_Is_Desktop_Viewer, CloudFront_Is_Mobile_Viewer, CloudFront_Is_SmartTV_Viewer"
   },
   {
    "name": "result_type",
    "label": "Response Result",
    "query": "SELECT DISTINCT (x_edge_detailed_result_type), count(*) AS CNT\nFROM $__database.$__table\nWHERE $__timeFilter\nGROUP BY x_edge_detailed_result_type\nORDER BY CNT DESC"
   },
   {
    "name": "distribution",
    "label": "Distribution",
    "query": "SELECT DISTINCT (x_host_header ), count(*) AS CNT\nFROM $__database.$__table\nWHERE $__timeFilter\nGROUP BY x_host_header \nORDER BY CNT DESC"
   },
   {
    "name": "streaming_format",
    "label": "Streaming format",
    "query": "SELECT DISTINCT (cmcd_streaming_format), count(*) AS CNT\nFROM $__database.$__table\nWHERE $__timeFilter\n               AND cmcd_streaming_format IN ('d','h','s','o')\nGROUP BY cmcd_streaming_format\nORDER BY CNT DESC"
   },
   {
    "name": "protocol",
    "label": "HTTP version",
    "query": "SELECT DISTINCT (cs_protocol), count(*) AS CNT\nFROM $__database.$__table\nWHERE $__timeFilter\nGROUP BY cs_protocol\nORDER BY CNT DESC"
   },
   {
    "name": "protocol_version",
    "label": "Protocol Version",
    "query": "SELECT DISTINCT (cs_protocol_version), count(*) AS CNT\nFROM $__database.$__table\nWHERE $__timeFilter\nGROUP BY cs_protocol_version\nORDER BY CNT DESC"
   }
  ]
 },
 "panels": [
  {
   "title": "Concurrent Plays",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"cmcd-db\"",
     "measure": "MULTI",
     "rawQuery": "SELECT COUNT (DISTINCT(cmcd_session_id)) AS Plays\nFROM $__database.$__table\nWHERE $__timeFilter\n      AND cmcd_session_id is not NULL\n      AND c_country IN (${country:singlequote})\n      AND 'true' IN (${device:csv})\n      AND x_host_header IN (${distribution:singlequote})\n      AND cmcd_streaming_format IN (${streaming_format:singlequote})\n      AND COALESCE (asn, '') IN (${asn:singlequote})\n      ",
     "table": "\"cmcd-table\""
    }
   ]
  },
  {
   "title": "Rebuffering percentage",
   "type": "gauge",
   "description": "Calculated as percentage of requests signalling rebuffering (CMCD bs) to the total number of requests.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"cmcd-db\"",
     "measure": "MULTI",
     "rawQuery": "SELECT COUNT (CASE WHEN cmcd_buffer_starvation = true THEN 1 ELSE Null END) / (1.0 * COUNT(x_edge_request_id)) * 100\nFROM $__database.$__table\nWHERE $__timeFilter\n      AND cmcd_session_id is not NULL\n      AND c_country IN (${country:singlequote})\n      AND 'true' IN (${device:csv})\n      AND x_host_header IN (${distribution:singlequote})\n      AND cmcd_streaming_format IN (${streaming_format:singlequote})\n      AND x_edge_detailed_result_type IN (${result_type:singlequote})\n      AND cs_protocol_version IN (${protocol_version:singlequote})\n      AND cs_protocol IN (${protocol:singlequote})\n      AND COALESCE (asn, '') IN (${asn:singlequote})",
     "table": "\"cmcd-table\""
    }
   ]
  },
  {
   "title": "Average Encoded Bitrate",
   "type": "stat",
   "description": "Average encoded bitrate of the video or video/audo objects ",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"cmcd-db\"",
     "measure": "MULTI",
     "rawQuery": "SELECT avg(cmcd_encoded_bitrate) AS Encoded_Bitrate\n-- approx_percentile(cmcd_encoded_bitrate, $percentile/100) AS Encoded_Bitrate\nFROM $__database.$__table\nWHERE $__timeFilter\n      AND cmcd_encoded_bitrate is not NULL\n      AND c_country IN (${country:singlequote})\n      AND 'true' IN (${device:csv})\n      AND x_host_header IN (${distribution:singlequote})\n      AND cmcd_streaming_format IN (${streaming_format:singlequote})\n      AND (cmcd_object_type = 'v' OR cmcd_object_type = 'av')\n      AND COALESCE (asn, '') IN (${asn:singlequote})",
     "table": "\"cmcd-table\""
    }
   ]
  },
  {
   "title": "Average Play duration",
   "type": "stat",
   "description": "Average Play duration estimated from the sum of all video or video/audio objects duration",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"cmcd-db\"",
     "measure": "MULTI",
     "rawQuery": "\nWITH CTE AS (\n      SELECT SUM(cmcd_object_duration) as duration, cmcd_session_id\n      FROM \"cmcd-db\".\"cmcd-table\"\n      WHERE $__timeFilter\n            AND cmcd_session_id is not NULL\n            AND c_country IN (${country:singlequote})\n            AND 'true' IN (${device:csv})\n            AND x_host_header IN (${distribution:singlequote})\n            AND cmcd_streaming_format IN (${streaming_format:singlequote})\n            AND (cmcd_object_type = 'v' OR cmcd_object_type = 'av')\n            AND COALESCE (asn, '') IN (${asn:singlequote})\n      GROUP BY cmcd_session_id\n) \nSELECT AVG(duration)\nFROM CTE\n",
     "table": "\"cmcd-table\""
    }
   ]
  },
  {
   "title": "Average Measured Throughput ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"cmcd-db\"",
     "measure": "MULTI",
     "rawQuery": "\nSELECT AVG(cmcd_measured_throughput)\nFROM $__database.$__table\nWHERE $__timeFilter\n      AND cmcd_measured_throughput is not NULL\n      AND c_country IN (${country:singlequote})\n      AND 'true' IN (${device:csv})\n      AND x_host_header IN (${distribution:singlequote})\n      AND cmcd_streaming_format IN (${streaming_format:singlequote})\n      AND x_edge_detailed_result_type IN (${result_type:singlequote})\n      AND cs_protocol_version IN (${protocol_version:singlequote})\n      AND cs_protocol IN (${protocol:singlequote})\n      AND COALESCE (asn, '') IN (${asn:singlequote})",
     "table": "\"cmcd-table\""
    }
   ]
  },
  {
   "title": "Streaming formats",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"cmcd-db\"",
     "measure": "MULTI",
     "rawQuery": "\n    SELECT COUNT(DISTINCT cmcd_session_id) AS Plays, cmcd_streaming_format AS streaming_format\n    FROM $__database.$__table\n    WHERE $__timeFilter\n          AND cmcd_streaming_format IN ('d','h','s','o')\n          AND c_country IN (${country:singlequote})\n          AND 'true' in (${device:csv})\n          AND x_host_header IN (${distribution:singlequote})\n          AND COALESCE (asn, '') IN (${asn:singlequote})\n    GROUP BY cmcd_streaming_format\n\n",
     "table": "\"cmcd-table\""
    }
   ]
  },
  { "title": "Quality of experience", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Buffer Length",
   "type": "barchart",
   "description": "Buffer Length p50 per Country",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "database": "\"cmcd-db\"",
     "measure": "MULTI",
     "rawQuery": "WITH binned_query AS (\n    SELECT c_country as Country, BIN(time, ${interval}) AS bin_time, approx_percentile(cmcd_buffer_length, $percentile * 0.01) as buff_length\n    FROM $__database.$__table\n    WHERE $__timeFilter\n        AND cmcd_buffer_length is not Null\n        AND c_country IN (${country:singlequote})\n        AND 'true' IN (${device:csv})\n        AND x_host_header IN (${distribution:singlequote})\n        AND cmcd_streaming_format IN (${streaming_format:singlequote})\n        AND COALESCE (asn, '') IN (${asn:singlequote})\n    GROUP BY c_country, BIN(time, ${interval})\n    ORDER BY bin_time\n)\nSELECT CREATE_TIME_SERIES(bin_time, buff_length) as Buffer_Length, Country\nFROM binned_query\nGROUP BY Country",
     "table": "\"cmcd-table\""
    }
   ]
  },
  {
   "title": "Measured Throughput",
   "type": "timeseries",
   "description": "Measured Throughput  by Object Type",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "database": "\"cmcd-db\"",
     "measure": "MULTI",
     "rawQuery": "WITH binned_query AS (\n    SELECT BIN(time, ${interval}) AS bin_time\n           ,approx_percentile(cmcd_measured_throughput, $percentile * 0.01) AS tput\n          ,cmcd_object_type\n    FROM $__database.$__table\n    WHERE $__timeFilter\n          AND cmcd_measured_throughput is not Null\n          AND cmcd_object_type is not Null\n          AND c_country IN (${country:singlequote})\n          AND 'true' IN (${device:csv})\n          AND x_host_header IN (${distribution:singlequote})\n          AND cmcd_streaming_format IN (${streaming_format:singlequote})\n          AND x_edge_detailed_result_type IN (${result_type:singlequote})\n          AND cs_protocol_version IN (${protocol_version:singlequote})\n          AND cs_protocol IN (${protocol:singlequote})\n          AND COALESCE (asn, '') IN (${asn:singlequote})\nGROUP BY cmcd_object_type, BIN(time, ${interval})\nORDER BY bin_time DESC\n)\nSELECT CREATE_TIME_SERIES(bin_time, tput) as Measured_Throughput, cmcd_object_type\nFROM binned_query\nGROUP BY cmcd_object_type",
     "table": "\"cmcd-table\""
    }
   ]
  },
  {
   "title": "Buffer Starvation Events",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "\"cmcd-db\"",
     "measure": "MULTI",
     "rawQuery": "WITH binned_query AS (\n    SELECT c_country AS Country, BIN(time, ${interval}) AS bin_time, \n    COUNT (CASE WHEN cmcd_buffer_starvation = true THEN 1 ELSE Null END) as bs\n    FROM $__database.$__table\n    WHERE $__timeFilter\n          AND c_country IN (${country:singlequote})\n          AND 'true' IN (${device:csv})\n          AND x_host_header IN (${distribution:singlequote})\n          AND cmcd_streaming_format IN (${streaming_format:singlequote})\n          AND x_edge_detailed_result_type IN (${result_type:singlequote})\n          AND cs_protocol_version IN (${protocol_version:singlequote})\n          AND cs_protocol IN (${protocol:singlequote})\n          AND COALESCE (asn, '') IN (${asn:singlequote})\nGROUP BY c_country, BIN(time, ${interval})\nORDER BY bin_time DESC\n)\nSELECT CREATE_TIME_SERIES(bin_time, bs) as Buffer_Starvation, Country\nFROM binned_query\nGROUP BY Country",
     "table": "\"cmcd-table\""
    }
   ]
  },
  { "title": "Traffic figures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Total Throughput",
   "type": "timeseries",
   "description": "Total throughput as estimated from amount of bytes sent to the viewers.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "database": "\"cmcd-db\"",
     "measure": "MULTI",
     "rawQuery": "WITH binned_query AS (  \n        SELECT BIN(time, 1s) AS bin_time, sum(sc_bytes) * 1.0 as Bytes_Downloaded\n        FROM $__database.$__table\n        WHERE $__timeFilter\n                AND c_country IN (${country:singlequote})\n                AND 'true' IN (${device:csv})\n                AND x_host_header IN (${distribution:singlequote})\n                AND COALESCE (asn, '') IN (${asn:singlequote})         \nGROUP BY BIN(time, 1s)\n)\n\nSELECT bin_time, (Bytes_Downloaded * 8 / 1048576)  as Throughput\nFROM binned_query\nORDER BY bin_time DESC\n",
     "table": "\"cmcd-table\""
    }
   ]
  },
  {
   "title": "Total Measured Throughput",
   "type": "timeseries",
   "description": "Total throughput as measured by client devices.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "database": "\"cmcd-db\"",
     "measure": "MULTI",
     "rawQuery": "\nWITH binned_query AS (\n      SELECT BIN(time, 1s) AS bin_time, avg(cmcd_measured_throughput) as measured_tput, cmcd_session_id\n      FROM $__database.$__table\n      WHERE $__timeFilter\n            AND cmcd_measured_throughput is NOT NULL\n            AND c_country IN (${country:singlequote})\n            AND 'true' IN (${device:csv})\n            AND x_host_header IN (${distribution:singlequote})\n            AND cmcd_streaming_format IN (${streaming_format:singlequote})\n            AND COALESCE (asn, '') IN (${asn:singlequote})\n      GROUP BY BIN(time, 1s), cmcd_session_id\n)\n\nSELECT bin_time, sum(measured_tput) as measured_tput_total\nFROM binned_query\nGROUP BY bin_time\nORDER BY bin_time DESC\n\n",
     "table": "\"cmcd-table\""
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "\"cmcd-db\"",
     "measure": "MULTI",
     "rawQuery": "\nSELECT BIN(time, 1s) AS bin_time, COUNT(x_edge_request_id) AS Requests\nFROM $__database.$__table\nWHERE $__timeFilter\n      AND c_country IN (${country:singlequote})\n      AND 'true' IN (${device:csv})\n      AND x_host_header IN (${distribution:singlequote})\n      AND COALESCE (asn, '') IN (${asn:singlequote})\nGROUP BY BIN(time, 1s)\nORDER BY BIN(time, 1s) DESC\n",
     "table": "\"cmcd-table\""
    }
   ]
  },
  {
   "title": "Origin Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "database": "\"cmcd-db\"",
     "measure": "MULTI",
     "rawQuery": "WITH binned_query AS (\nSELECT BIN(time, ${interval}) AS bin_time, sum(sc_bytes) * 1.0 as Bytes_Downloaded\nFROM $__database.$__table\nWHERE $__timeFilter\n      AND c_country IN (${country:singlequote})\n      AND 'true' IN (${device:csv})\n      AND x_host_header IN (${distribution:singlequote})\n      AND x_edge_response_result_type in ('Miss', 'PrefetchMiss', 'RefreshHit')\n      AND COALESCE (asn, '') IN (${asn:singlequote})\nGROUP BY BIN(time, ${interval})\n)\nSELECT bin_time, (Bytes_Downloaded * 8 / 1048576) / 60 as Throughput\nFROM binned_query\nORDER BY bin_time DESC\n",
     "table": "\"cmcd-table\""
    }
   ]
  },
  {
   "title": "Plays by GEO",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "database": "\"cmcd-db\"",
     "measure": "MULTI",
     "rawQuery": "SELECT COUNT(DISTINCT(cmcd_session_id)) as Plays, c_country as Country\nFROM $__database.$__table\nWHERE $__timeFilter\n--      AND c_country != '-'\n        AND 'true' IN (${device:csv})\n        AND x_host_header IN (${distribution:singlequote})\n        AND cmcd_streaming_format IN (${streaming_format:singlequote})\n        AND COALESCE (asn, '') IN (${asn:singlequote})\nGROUP BY c_country",
     "table": "\"cmcd-table\""
    }
   ]
  },
  {
   "title": "Plays by PoP",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "database": "\"cmcd-db\"",
     "measure": "MULTI",
     "rawQuery": "WITH CTE as (\n      SELECT regexp_extract(x_edge_location, '([A-Z]{3}).*', 1) as PoP\n             ,COUNT(DISTINCT(cmcd_session_id)) as CNT\n      FROM $__database.$__table\n      WHERE $__timeFilter\n            AND cmcd_session_id is not Null\n            AND 'true' IN (${device:csv})\n            AND x_host_header IN (${distribution:singlequote})\n            AND cmcd_streaming_format IN (${streaming_format:singlequote})\n            AND COALESCE (asn, '') IN (${asn:singlequote})\n      GROUP BY x_edge_location\n)\nSELECT sum(CNT), PoP\nFROM CTE\nGROUP BY PoP",
     "table": "\"cmcd-table\""
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "database": "\"cmcd-db\"",
     "measure": "MULTI",
     "rawQuery": "\nSELECT count_if (x_edge_response_result_type = 'Hit') / (1.0 * count (x_edge_request_id)) * 100 AS chr\n     ,BIN(time, ${interval})\nFROM $__database.$__table\nWHERE $__timeFilter\n     AND c_country IN (${country:singlequote})\n     AND 'true' IN (${device:csv})\n     AND x_host_header IN (${distribution:singlequote})\n     AND COALESCE (asn, '') IN (${asn:singlequote})\nGROUP BY BIN(time, ${interval})\nORDER BY BIN(time, ${interval}) DESC\n",
     "table": "\"cmcd-table\""
    }
   ]
  },
  {
   "title": "Bytes per Edge Location",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "database": "\"cmcd-db\"",
     "measure": "MULTI",
     "rawQuery": "WITH binned_query AS (\nSELECT x_edge_location AS Edge, BIN(time, ${interval}) AS bin_time, sum(sc_bytes) AS Bytes\nFROM $__database.$__table\nWHERE $__timeFilter\n      AND c_country IN (${country:singlequote})\n      AND 'true' IN (${device:csv})\n      AND x_host_header IN (${distribution:singlequote})\n      AND COALESCE (asn, '') IN (${asn:singlequote})\nGROUP BY x_edge_location, BIN(time, ${interval})\norder by bin_time DESC\n)\nSELECT Edge, CREATE_TIME_SERIES(bin_time, Bytes) AS Bytes_Downloaded\nFROM binned_query\nGROUP BY Edge",
     "table": "\"cmcd-table\""
    }
   ]
  }
 ]
}