{
 "title": "Troubleshooting",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m, 5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "country",
    "label": "Country",
    "query": "SELECT DISTINCT (c_country), count(*) AS CNT\nFROM $__database.$__table\nWHERE $__timeFilter\nGROUP BY c_country\nORDER BY CNT DESC"
   },
   {
    "name": "asn",
    "label": "ASN",
    "query": "SELECT DISTINCT (asn), count(*) AS CNT\nFROM $__database.$__table\nWHERE $__timeFilter\nGROUP BY asn\nORDER BY CNT DESC"
   },
   {
    "name": "device",
    "label": "Device  Type",
    "query": "CloudFront_Is_Desktop_Viewer, CloudFront_Is_Mobile_Viewer, CloudFront_Is_SmartTV_Viewer"
   },
   {
    "name": "edge_location",
    "label": "Edge Location",
    "query": "SELECT DISTINCT (x_edge_location), count(*) AS CNT\nFROM $__database.$__table\nWHERE $__timeFilter\nGROUP BY x_edge_location\nORDER BY CNT DESC"
   },
   {
    "name": "result_type",
    "label": "Response Result",
    "query": "SELECT DISTINCT (x_edge_detailed_result_type), count(*) AS CNT\nFROM $__database.$__table\nWHERE $__timeFilter\nGROUP BY x_edge_detailed_result_type\nORDER BY CNT DESC"
   },
   {
    "name": "status_code",
    "label": "HTTP code",
    "query": "SELECT DISTINCT (sc_status), count(*) AS CNT\nFROM $__database.$__table\nWHERE $__timeFilter\nGROUP BY sc_status\nORDER BY CNT DESC"
   },
   {
    "name": "distribution",
    "label": "Distribution",
    "query": "SELECT DISTINCT (x_host_header ), count(*) AS CNT\nFROM $__database.$__table\nWHERE $__timeFilter\nGROUP BY x_host_header \nORDER BY CNT DESC"
   },
   {
    "name": "streaming_format",
    "label": "Streaming format",
    "query": "SELECT DISTINCT (cmcd_sf), count(*) AS CNT\nFROM $__database.$__table\nWHERE $__timeFilter\n               AND cmcd_sf is not NULL\nGROUP BY cmcd_sf\nORDER BY CNT DESC"
   },
   {
    "name": "protocol",
    "label": "HTTP version",
    "query": "SELECT DISTINCT (cs_protocol), count(*) AS CNT\nFROM $__database.$__table\nWHERE $__timeFilter\nGROUP BY cs_protocol\nORDER BY CNT DESC"
   },
   {
    "name": "protocol_version",
    "label": "Protocol Version",
    "query": "SELECT DISTINCT (cs_protocol_version), count(*) AS CNT\nFROM $__database.$__table\nWHERE $__timeFilter\nGROUP BY cs_protocol_version\nORDER BY CNT DESC"
   }
  ]
 },
 "panels": [
  {
   "title": "Rebuffering Sessions",
   "type": "timeseries",
   "description": "This query is calculating the ratio of plays with > 1% of rebuffering events to the total nimber of plays within this sessions.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "database": "\"cmcd-db\"",
     "measure": "MULTI",
     "rawQuery": "WITH rebuffering_sessions\nAS (\n    SELECT cmcd_sid AS plays\n           ,BIN(time, ${interval}) AS bin_time\n           ,CASE WHEN count_if(cmcd_bs) >= 0.01 * count (x_edge_request_id) THEN 'BS' ELSE 'NO-BS' END as BS\n    FROM $__database.$__table\n    WHERE $__timeFilter\n          AND cmcd_sid IS NOT NULL\n          AND c_country IN (${country:singlequote})\n          AND x_edge_location IN (${edge_location:singlequote})\n          AND cs_protocol_version IN (${protocol_version:singlequote})\n          AND cs_protocol IN (${protocol:singlequote})\n          AND 'true' IN (${device:csv})\n          AND x_host_header IN (${distribution:singlequote})\n          AND cmcd_sf IN (${streaming_format:singlequote})\n          AND COALESCE (asn, '') IN (${asn:singlequote})\n          \n    GROUP BY BIN(time, ${interval}), cmcd_sid\n)\nSELECT bin_time\n      ,ROUND(COUNT (CASE WHEN BS = 'BS' THEN 1 ELSE Null END) / (1.0 * NULLIF(COUNT (plays), 0)) * 100) as rebuffering_ratio\nFROM rebuffering_sessions\nGROUP BY bin_time\nORDER BY bin_time DESC",
     "table": "\"cmcd-table\""
    }
   ]
  },
  {
   "title": "Rebuffering Events Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "\"cmcd-db\"",
     "measure": "MULTI",
     "rawQuery": "WITH rebuffering_events AS (\n      SELECT time\n            ,cmcd_bs\n            ,x_edge_request_id\n            ,x_edge_detailed_result_type AS detailed_result_type \n            ,LAG(x_edge_detailed_result_type, 1) OVER (PARTITION BY cmcd_sid ORDER BY time) as detailed_result_type_prev\n            ,LAG(sc_status, 1) OVER (PARTITION BY cmcd_sid ORDER BY time) as http_status_prev\n      FROM $__database.$__table\n      WHERE $__timeFilter\n            AND cmcd_sid is not Null\n            AND c_country IN (${country:singlequote})\n            AND x_edge_location IN (${edge_location:singlequote})\n            AND cs_protocol_version IN (${protocol_version:singlequote})\n            AND cs_protocol IN (${protocol:singlequote})\n            AND 'true' IN (${device:csv})\n            AND x_host_header IN (${distribution:singlequote})\n            AND cmcd_sf IN (${streaming_format:singlequote})\n            AND COALESCE (asn, '') IN (${asn:singlequote})\n)\n\nSELECT COUNT (CASE WHEN cmcd_bs = true THEN 1 ELSE Null END)\n      ,BIN(time, ${interval})  \nFROM rebuffering_events\nWHERE detailed_result_type_prev IN (${result_type:singlequote}, Null)\n      AND http_status_prev IN (${status_code:singlequote}, Null)\nGROUP BY BIN(time, ${interval}) \nORDER BY BIN(time, ${interval}) DESC\n",
     "table": "\"cmcd-table\""
    }
   ]
  },
  {
   "title": "Rebuffering Events Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "database": "\"cmcd-db\"",
     "measure": "MULTI",
     "rawQuery": "WITH rebuffering_events AS (\n      SELECT time\n            ,cmcd_bs\n            ,x_edge_request_id\n            ,x_edge_detailed_result_type AS detailed_result_type \n            ,LAG(x_edge_detailed_result_type, 1) OVER (PARTITION BY cmcd_sid ORDER BY time) as detailed_result_type_prev\n            ,LAG(sc_status, 1) OVER (PARTITION BY cmcd_sid ORDER BY time) as http_status_prev\n      FROM $__database.$__table\n      WHERE $__timeFilter\n            AND cmcd_sid is not Null\n            AND c_country IN (${country:singlequote})\n            AND x_edge_location IN (${edge_location:singlequote})\n            AND cs_protocol_version IN (${protocol_version:singlequote})\n            AND cs_protocol IN (${protocol:singlequote})\n            AND 'true' IN (${device:csv})\n            AND x_host_header IN (${distribution:singlequote})\n            AND cmcd_sf IN (${streaming_format:singlequote})\n            AND COALESCE (asn, '') IN (${asn:singlequote})\n)\n\nSELECT COUNT (CASE WHEN cmcd_bs = true THEN 1 ELSE Null END) / (1.0 * COUNT(x_edge_request_id)) * 100 as rebuffering_events\n      ,BIN(time, ${interval})  \nFROM rebuffering_events\nWHERE detailed_result_type_prev IN (${result_type:singlequote}, Null)\n      AND http_status_prev IN (${status_code:singlequote}, Null)\nGROUP BY BIN(time, ${interval}) \nORDER BY BIN(time, ${interval}) DESC\n",
     "table": "\"cmcd-table\""
    }
   ]
  },
  {
   "title": "Rebuffering Events Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "database": "\"cmcd-db\"",
     "measure": "MULTI",
     "rawQuery": "WITH CTE AS (\n      SELECT time\n             ,cmcd_sid\n             ,c_country\n\t      ,CASE WHEN cmcd_bs=true THEN LAG(x_edge_request_id, 1) OVER (PARTITION BY cmcd_sid ORDER BY time)  END AS CF_request_id\n            ,CASE WHEN cmcd_bs=true THEN LAG(regexp_replace(cs_uri_stem, '\\?(.*)'), 1) OVER (PARTITION BY cmcd_sid ORDER BY time) END AS uri\n            ,CASE WHEN cmcd_bs=true THEN LAG(cmcd_mtp, 1) OVER (PARTITION BY cmcd_sid ORDER BY time) END AS throughput\n            ,CASE WHEN cmcd_bs=true THEN LAG(x_edge_detailed_result_type, 1) OVER (PARTITION BY cmcd_sid ORDER BY time) END AS result_type\n            ,CASE WHEN cmcd_bs=true THEN LAG(c_ip, 1) OVER (PARTITION BY cmcd_sid ORDER BY time) END AS client_ip\n            ,CASE WHEN cmcd_bs=true THEN LAG(sc_status, 1) OVER (PARTITION BY cmcd_sid ORDER BY time) END AS http_code\n            ,CASE WHEN cmcd_bs=true THEN LAG(asn, 1) OVER (PARTITION BY cmcd_sid ORDER BY time) END AS asn\n\nFROM $__database.$__table\nWHERE $__timeFilter\n      AND cmcd_sid is not Null\n      AND c_country IN (${country:singlequote})\n      AND x_edge_location IN (${edge_location:singlequote})\n      AND cs_protocol_version IN (${protocol_version:singlequote})\n      AND cs_protocol IN (${protocol:singlequote})\n      AND 'true' IN (${device:csv})\n      AND x_host_header IN (${distribution:singlequote})\n      AND cmcd_sf IN (${streaming_format:singlequote})\n      AND COALESCE (asn, '') IN (${asn:singlequote})\n)\n\nSELECT time, c_country, asn, cmcd_sid, CF_request_id, uri, throughput, result_type, http_code, client_ip\nFROM CTE\nWHERE CF_request_id is not null\n      AND http_code IN (${status_code:singlequote})\n      AND result_type IN (${result_type:singlequote})\nORDER BY time DESC\n\n\n ",
     "table": "\"cmcd-table\""
    }
   ]
  },
  {
   "title": "Rebuffering Sessions vs  TTFB: HIT",
   "type": "timeseries",
   "description": "Number of Rebuffering Sessions vs TTFB for Cache Hit",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "\"cmcd-db\"",
     "measure": "MULTI",
     "rawQuery": "WITH rebuffering_sessions AS (\n      SELECT cmcd_sid AS plays\n            ,bin(time, ${interval}) AS bin_time\n            ,CASE WHEN count_if(cmcd_bs) >= 0.01 * count (x_edge_request_id) THEN 'BS' ELSE 'NO-BS' END as BS\n      FROM $__database.$__table\n      WHERE $__timeFilter\n            AND cmcd_sid IS NOT NULL\n            AND c_country IN (${country:singlequote})\n            AND x_edge_location IN (${edge_location:singlequote})\n            AND cs_protocol_version IN (${protocol_version:singlequote})\n            AND cs_protocol IN (${protocol:singlequote})\n            AND 'true' IN (${device:csv})\n            AND x_host_header IN (${distribution:singlequote})\n            AND cmcd_sf IN (${streaming_format:singlequote})\n            AND COALESCE (asn, '') IN (${asn:singlequote})\nGROUP BY bin(time, ${interval}), cmcd_sid\n)\nSELECT bin_time\n      ,ROUND(COUNT (CASE WHEN BS = 'BS' THEN 1 ELSE Null END) / (1.0 * NULLIF(COUNT (plays), 0)) * 100) as rebuffering_ratio\nFROM rebuffering_sessions\nGROUP BY bin_time\nORDER BY bin_time DESC\n",
     "table": "\"cmcd-table\""
    },
    {
     "database": "\"cmcd-db\"",
     "measure": "MULTI",
     "rawQuery": "WITH TTFB AS (\n      SELECT bin(time, ${interval}) AS bin_time\n            ,avg(time_to_first_byte) AS ttfb\n      FROM $__database.$__table\n      WHERE $__timeFilter\n            AND c_country IN (${country:singlequote})\n            AND x_edge_location IN (${edge_location:singlequote})\n            AND cs_protocol_version IN (${protocol_version:singlequote})\n            AND cs_protocol IN (${protocol:singlequote})\n            AND x_edge_detailed_result_type = 'Hit'\n      GROUP BY bin(time, ${interval})\n)\nSELECT bin_time\n      ,ttfb AS ttfb\n      ,avg(ttfb) OVER (\n\t\tORDER BY bin_time range BETWEEN unbounded preceding AND CURRENT row\n\t) AS moving_ttfb\nFROM TTFB\nORDER BY bin_time DESC",
     "table": "\"cmcd-table\""
    }
   ]
  },
  {
   "title": "Rebuffering Sessions vs TTFB: MISS",
   "type": "timeseries",
   "description": "Number of Rebuffering Sessions vs  TTFB for Cache Miss",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "\"cmcd-db\"",
     "measure": "MULTI",
     "rawQuery": "WITH rebuffering_sessions AS (\n      SELECT cmcd_sid as plays\n            ,bin(time, ${interval}) AS bin_time\n            ,CASE WHEN count_if(cmcd_bs) >= 0.01 * count (x_edge_request_id) THEN 'BS' ELSE 'NO-BS' END as BS\n      FROM $__database.$__table\n      WHERE $__timeFilter\n            AND cmcd_sid IS NOT NULL\n            AND c_country IN (${country:singlequote})\n            AND x_edge_location IN (${edge_location:singlequote})\n            AND cs_protocol_version IN (${protocol_version:singlequote})\n            AND cs_protocol IN (${protocol:singlequote})\n            AND 'true' IN (${device:csv})\n            AND x_host_header IN (${distribution:singlequote})\n            AND cmcd_sf IN (${streaming_format:singlequote})\n            AND COALESCE (asn, '') IN (${asn:singlequote})\n      GROUP BY bin(time, ${interval}), cmcd_sid\n)\nSELECT bin_time\n      ,ROUND(COUNT (CASE WHEN BS = 'BS' THEN 1 ELSE Null END) / (1.0 * NULLIF(COUNT (plays), 0)) * 100) as rebuffering_ratio\nFROM rebuffering_sessions\nGROUP BY bin_time\nORDER BY bin_time DESC\n",
     "table": "\"cmcd-table\""
    },
    {
     "database": "\"cmcd-db\"",
     "measure": "MULTI",
     "rawQuery": "WITH TTFB AS (\n      SELECT bin(time, ${interval}) AS bin_time\n            ,avg(time_to_first_byte) AS ttfb\n      FROM $__database.$__table\n      WHERE $__timeFilter\n            --AND x_edge_detailed_result_type IN ('Miss', 'OriginConnectError', 'OriginContentRangeLengthError',\n            --    'OriginDnsError', 'OriginError', 'OriginHeaderTooBigError', 'OriginInvalidResponseError',\n            --    'OriginReadError', 'OriginZeroSizeObjectError')\n            AND x_edge_detailed_result_type IN ('Miss')\n            AND c_country IN (${country:singlequote})\n            AND x_edge_location IN (${edge_location:singlequote})\n            AND cs_protocol_version IN (${protocol_version:singlequote})\n            AND cs_protocol IN (${protocol:singlequote})\n      GROUP BY bin(time, ${interval})\n)\nSELECT bin_time\n      ,ttfb AS ttfb\n      ,avg(ttfb) OVER (\n\t\tORDER BY bin_time range BETWEEN unbounded preceding AND CURRENT row\n\t) AS moving_ttfb\nFROM TTFB\nORDER BY bin_time DESC",
     "table": "\"cmcd-table\""
    }
   ]
  },
  {
   "title": "Rebuffering Sessions vs Rate of Change TTFB: HIT",
   "type": "timeseries",
   "description": "Number of Rebuffering Sessions vs TTFB Rate of Change",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "\"cmcd-db\"",
     "measure": "MULTI",
     "rawQuery": "WITH rebuffering_sessions\nAS (\n    SELECT cmcd_sid AS plays\n           ,BIN(time, ${interval}) AS bin_time\n           ,CASE WHEN count_if(cmcd_bs) >= 0.01 * count (x_edge_request_id) THEN 'BS' ELSE 'NO-BS' END AS BS\n    FROM $__database.$__table\n    WHERE $__timeFilter\n          AND cmcd_sid IS NOT NULL\n          AND c_country IN (${country:singlequote})\n          AND x_edge_location IN (${edge_location:singlequote})\n          AND cs_protocol_version IN (${protocol_version:singlequote})\n          AND cs_protocol IN (${protocol:singlequote})\n          AND 'true' IN (${device:csv})\n          AND x_host_header IN (${distribution:singlequote})\n          AND cmcd_sf IN (${streaming_format:singlequote})\n          AND COALESCE (asn, '') IN (${asn:singlequote})\n    GROUP BY BIN(time, ${interval}), cmcd_sid\n)\nSELECT bin_time\n      ,ROUND(COUNT (CASE WHEN BS = 'BS' THEN 1 ELSE Null END) / (1.0 * NULLIF(COUNT (plays), 0)) * 100) AS rebuffering_ratio\nFROM rebuffering_sessions\nGROUP BY bin_time\nORDER BY bin_time DESC",
     "table": "\"cmcd-table\""
    },
    {
     "database": "\"cmcd-db\"",
     "measure": "MULTI",
     "rawQuery": "WITH TTFB AS (\nSELECT bin(time, ${interval}) AS bin_time, avg(time_to_first_byte) AS ttfb\nFROM $__database.$__table\nWHERE $__timeFilter\n       AND c_country IN (${country:singlequote})\n       AND x_edge_detailed_result_type IN (${result_type:singlequote})\n       AND cs_protocol_version IN (${protocol_version:singlequote})\n       AND cs_protocol IN (${protocol:singlequote})\n       AND x_edge_detailed_result_type = 'Hit'\nGROUP BY bin(time, ${interval})\nORDER BY bin_time\n)\nSELECT derivative_linear(CREATE_TIME_SERIES(bin_time, ttfb), ${interval}) AS rateOfChange\n--non_negative_derivative_linear\nFROM TTFB",
     "table": "\"cmcd-table\""
    }
   ]
  },
  {
   "title": "Rebuffering Sessions vs Origin  TTFB",
   "type": "timeseries",
   "description": "Number of Rebuffering Sessions vs  Origin TTFB",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "\"cmcd-db\"",
     "measure": "MULTI",
     "rawQuery": "WITH rebuffering_sessions AS (\n      SELECT cmcd_sid as plays\n            ,bin(time, ${interval}) AS bin_time\n            ,CASE WHEN count_if(cmcd_bs) >= 0.01 * count (x_edge_request_id) THEN 'BS' ELSE 'NO-BS' END as BS\n      FROM $__database.$__table\n      WHERE $__timeFilter\n            AND cmcd_sid IS NOT NULL\n            AND c_country IN (${country:singlequote})\n            AND x_edge_location IN (${edge_location:singlequote})\n            AND cs_protocol_version IN (${protocol_version:singlequote})\n            AND cs_protocol IN (${protocol:singlequote})\n            AND 'true' IN (${device:csv})\n            AND x_host_header IN (${distribution:singlequote})\n            AND cmcd_sf IN (${streaming_format:singlequote})\n            AND COALESCE (asn, '') IN (${asn:singlequote})\n      GROUP BY bin(time, ${interval}), cmcd_sid\n)\nSELECT bin_time\n      ,ROUND(COUNT (CASE WHEN BS = 'BS' THEN 1 ELSE Null END) / (1.0 * NULLIF(COUNT (plays), 0)) * 100) as rebuffering_ratio\nFROM rebuffering_sessions\nGROUP BY bin_time\nORDER BY bin_time DESC\n",
     "table": "\"cmcd-table\""
    },
    {
     "database": "\"cmcd-db\"",
     "measure": "MULTI",
     "rawQuery": "WITH TTFB AS (\n      SELECT bin(time, ${interval}) AS bin_time\n            ,avg(origin_fbl) AS origin_ttfb\n      FROM $__database.$__table\n      WHERE $__timeFilter\n            AND origin_fbl is not Null\n            AND c_country IN (${country:singlequote})\n            AND x_edge_location IN (${edge_location:singlequote})\n            AND cs_protocol_version IN (${protocol_version:singlequote})\n            AND cs_protocol IN (${protocol:singlequote})\n      GROUP BY bin(time, ${interval})\n)\nSELECT bin_time\n      ,origin_ttfb\n      ,avg(origin_ttfb) OVER (\n\t\tORDER BY bin_time range BETWEEN unbounded preceding AND CURRENT row\n\t) AS moving_origin_ttfb\nFROM TTFB\nORDER BY bin_time DESC",
     "table": "\"cmcd-table\""
    }
   ]
  },
  {
   "title": "Rebuffering Sessions vs Rate of Change TTFB: MISS",
   "type": "timeseries",
   "description": "Number of Rebuffering Sessions vs TTFB Rate of Change",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "\"cmcd-db\"",
     "measure": "MULTI",
     "rawQuery": "WITH rebuffering_sessions\nAS (\n    SELECT cmcd_sid AS plays\n           ,BIN(time, ${interval}) AS bin_time\n           ,CASE WHEN count_if(cmcd_bs) >= 0.01 * count (x_edge_request_id) THEN 'BS' ELSE 'NO-BS' END AS BS\n    FROM $__database.$__table\n    WHERE $__timeFilter\n          AND cmcd_sid IS NOT NULL\n          AND c_country IN (${country:singlequote})\n          AND x_edge_location IN (${edge_location:singlequote})\n          AND cs_protocol_version IN (${protocol_version:singlequote})\n          AND cs_protocol IN (${protocol:singlequote})\n          AND 'true' IN (${device:csv})\n          AND x_host_header IN (${distribution:singlequote})\n          AND cmcd_sf IN (${streaming_format:singlequote})\n          AND COALESCE (asn, '') IN (${asn:singlequote})\n    GROUP BY BIN(time, ${interval}), cmcd_sid\n)\nSELECT bin_time\n      ,ROUND(COUNT (CASE WHEN BS = 'BS' THEN 1 ELSE Null END) / (1.0 * NULLIF(COUNT (plays), 0)) * 100) AS rebuffering_ratio\nFROM rebuffering_sessions\nGROUP BY bin_time\nORDER BY bin_time DESC",
     "table": "\"cmcd-table\""
    },
    {
     "database": "\"cmcd-db\"",
     "measure": "MULTI",
     "rawQuery": "WITH TTFB AS (\nSELECT bin(time, ${interval}) AS bin_time, avg(time_to_first_byte) AS ttfb\nFROM $__database.$__table\nWHERE $__timeFilter\n       AND c_country IN (${country:singlequote})\n       AND x_edge_location IN (${edge_location:singlequote})\n       AND x_edge_detailed_result_type IN (${result_type:singlequote})\n       AND cs_protocol_version IN (${protocol_version:singlequote})\n       AND cs_protocol IN (${protocol:singlequote})\n       AND x_edge_detailed_result_type = 'Miss'\nGROUP BY bin(time, ${interval})\nORDER BY bin_time\n)\nSELECT derivative_linear(CREATE_TIME_SERIES(bin_time, ttfb), ${interval}) AS rateOfChange\n--non_negative_derivative_linear\nFROM TTFB",
     "table": "\"cmcd-table\""
    }
   ]
  },
  {
   "title": "Rebuffering Sessions vs MTP",
   "type": "timeseries",
   "description": "Number of Rebuffering Sessions vs Measured Throughput",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "\"cmcd-db\"",
     "measure": "MULTI",
     "rawQuery": "WITH rebuffering_sessions AS (\n      SELECT cmcd_sid as plays\n            ,bin(time, ${interval}) AS bin_time\n            ,CASE WHEN count_if(cmcd_bs) >= 0.01 * count (x_edge_request_id) THEN 'BS' ELSE 'NO-BS' END AS BS\n      FROM $__database.$__table\n      WHERE $__timeFilter\n            AND cmcd_sid IS NOT NULL\n            AND c_country IN (${country:singlequote})\n            AND x_edge_location IN (${edge_location:singlequote})\n            AND cs_protocol_version IN (${protocol_version:singlequote})\n            AND cs_protocol IN (${protocol:singlequote})\n            AND 'true' IN (${device:csv})\n            AND x_host_header IN (${distribution:singlequote})\n            AND cmcd_sf IN (${streaming_format:singlequote})\n            AND COALESCE (asn, '') IN (${asn:singlequote})\n      GROUP BY bin(time, ${interval}), cmcd_sid\n)\nSELECT bin_time\n      ,ROUND(COUNT (CASE WHEN BS = 'BS' THEN 1 ELSE Null END) / (1.0 * NULLIF(COUNT (plays), 0)) * 100) as rebuffering_ratio\nFROM rebuffering_sessions\nGROUP BY bin_time\nORDER BY bin_time DESC\n",
     "table": "\"cmcd-table\""
    },
    {
     "database": "\"cmcd-db\"",
     "measure": "MULTI",
     "rawQuery": "\nWITH CTE AS (\nSELECT \n        time\n       ,CASE WHEN LAG(x_edge_detailed_result_type, 1)  OVER (PARTITION BY cmcd_sid ORDER BY time) = 'Hit' THEN LAG(cmcd_mtp, 1) OVER (PARTITION BY cmcd_sid ORDER BY time) END as mtp_hit\n       ,CASE WHEN LAG(x_edge_detailed_result_type, 1)  OVER (PARTITION BY cmcd_sid ORDER BY time) = 'Miss' THEN LAG(cmcd_mtp, 1) OVER (PARTITION BY cmcd_sid ORDER BY time) END as mtp_miss\nFROM $__database.$__table\nWHERE $__timeFilter\n      AND c_country IN (${country:singlequote})\n      AND x_edge_location IN (${edge_location:singlequote})\n      AND cs_protocol_version IN (${protocol_version:singlequote})\n      AND cs_protocol IN (${protocol:singlequote})\n)\n\nSELECT bin(time, ${interval}) AS bin_time\n       ,avg(mtp_hit) AS mtp_hit_avg\n       ,avg(mtp_miss) AS mtp_miss_avg\nFROM CTE\nGROUP BY bin(time, ${interval})\nORDER BY bin(time, ${interval}) DESC",
     "table": "\"cmcd-table\""
    }
   ]
  },
  {
   "title": "Row logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {
     "database": "\"cmcd-db\"",
     "measure": "MULTI",
     "rawQuery": "SELECT cs_uri_stem, $__database.$__table.*\nFROM $__database.$__table\nWHERE $__timeFilter\n        AND c_country IN (${country:singlequote})\n        AND 'true' IN (${device:csv})\n        AND x_host_header IN (${distribution:singlequote})\n        AND cmcd_sf IN (${streaming_format:singlequote})\n        AND x_edge_detailed_result_type IN (${result_type:singlequote})\n        AND cs_protocol_version IN (${protocol_version:singlequote})\n        AND cs_protocol IN (${protocol:singlequote})\n        AND COALESCE (asn, '') IN (${asn:singlequote})\nORDER BY time DESC\nLIMIT 100",
     "table": "\"cmcd-table\""
    }
   ]
  }
 ]
}